# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YPShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YPShop
pod 'Alamofire'
pod 'Swinject'

  target 'YPShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YPShopUITests' do
    # Pods for testing
  end

end
